version: 2.1

orbs:
  prodsec: snyk/prodsec-orb@1

commands:
  go_mod_download:
    description: Go modules cache with private modules handling
    steps:
      - go/mod-download-cached:
          basic-auth-secret: GITHUB_PRIVATE_TOKEN
          module-path: github.com/snyk

jobs:
  security-scans:
    resource_class: small
    docker:
      - image: cimg/go:1.21
    steps:
      - checkout
      - go_mod_download
      - prodsec/security_scans:
          mode: auto
          open-source-additional-arguments: --exclude=testdata
          iac-scan: disabled

workflows:
  version: 2
  CICD:
    jobs:
      - prodsec/secrets-scan:
          name: Scan repository for secrets
          context:
            - snyk-bot-slack
          channel: snyk-on-snyk-productinfra_agentic-dev
          filters:
            branches:
              ignore:
                - main  
          
      - security-scans:
          context: productinfra-agentic-dev-sos
