// Package v20241015 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.5.1 DO NOT EDIT.
package v20241015

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for BreakabilityResponseAttributesRiskLevel.
const (
	High   BreakabilityResponseAttributesRiskLevel = "high"
	Low    BreakabilityResponseAttributesRiskLevel = "low"
	Medium BreakabilityResponseAttributesRiskLevel = "medium"
)

// Defines values for CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONBodyDataType.
const (
	Breakability CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONBodyDataType = "breakability"
)

// ActualVersion Resolved API version
type ActualVersion = string

// BreakabilityResponseAttributes defines model for BreakabilityResponseAttributes.
type BreakabilityResponseAttributes struct {
	// PublicId The stable identifier of the persisted assessment. Only present when the assessment was successfully stored in the db. Absent if the db write failed.
	PublicId *openapi_types.UUID `json:"public_id,omitempty"`

	// RiskLevel The estimated breakability risk level of the analyzed package upgrades.
	RiskLevel BreakabilityResponseAttributesRiskLevel `json:"risk_level"`

	// Summary A breakability assessment summary, outlining reasoning for the estimated risk_level and possible mitigations.
	Summary string `json:"summary"`
}

// BreakabilityResponseAttributesRiskLevel The estimated breakability risk level of the analyzed package upgrades.
type BreakabilityResponseAttributesRiskLevel string

// Error defines model for Error.
type Error struct {
	// Code An application-specific error code, expressed as a string value.
	Code *string `json:"code,omitempty"`

	// Detail A human-readable explanation specific to this occurrence of the problem.
	Detail string `json:"detail"`

	// Id A unique identifier for this particular occurrence of the problem.
	Id *openapi_types.UUID `json:"id,omitempty"`

	// Links A link that leads to further details about this particular occurrance of the problem.
	Links  *ErrorLink              `json:"links,omitempty"`
	Meta   *map[string]interface{} `json:"meta,omitempty"`
	Source *struct {
		// Parameter A string indicating which URI query parameter caused the error.
		Parameter *string `json:"parameter,omitempty"`

		// Pointer A JSON Pointer [RFC6901] to the associated entity in the request document.
		Pointer *string `json:"pointer,omitempty"`
	} `json:"source,omitempty"`

	// Status The HTTP status code applicable to this problem, expressed as a string value.
	Status string `json:"status"`

	// Title A short, human-readable summary of the problem that SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization.
	Title *string `json:"title,omitempty"`
}

// ErrorDocument defines model for ErrorDocument.
type ErrorDocument struct {
	Errors  []Error `json:"errors"`
	Jsonapi JsonApi `json:"jsonapi"`
}

// ErrorLink A link that leads to further details about this particular occurrance of the problem.
type ErrorLink struct {
	About *LinkProperty `json:"about,omitempty"`
}

// JsonApi defines model for JsonApi.
type JsonApi struct {
	// Version Version of the JSON API specification this server supports.
	Version string `json:"version"`
}

// LinkProperty defines model for LinkProperty.
type LinkProperty struct {
	union json.RawMessage
}

// LinkProperty0 A string containing the link’s URL.
type LinkProperty0 = string

// LinkProperty1 defines model for .
type LinkProperty1 struct {
	// Href A string containing the link’s URL.
	Href string `json:"href"`

	// Meta Free-form object that may contain non-standard information.
	Meta *Meta `json:"meta,omitempty"`
}

// Meta Free-form object that may contain non-standard information.
type Meta map[string]interface{}

// PaginatedLinks defines model for PaginatedLinks.
type PaginatedLinks struct {
	First *LinkProperty `json:"first,omitempty"`
	Last  *LinkProperty `json:"last,omitempty"`
	Next  *LinkProperty `json:"next,omitempty"`
	Prev  *LinkProperty `json:"prev,omitempty"`
	Self  *LinkProperty `json:"self,omitempty"`
}

// QueryVersion Requested API version
type QueryVersion = string

// Types defines model for Types.
type Types = string

// Upgrade defines model for Upgrade.
type Upgrade struct {
	FromVersion string `json:"from_version"`
	Name        string `json:"name"`
	ToVersion   string `json:"to_version"`
}

// Version Requested API version
type Version = QueryVersion

// N400 defines model for 400.
type N400 = ErrorDocument

// N401 defines model for 401.
type N401 = ErrorDocument

// N403 defines model for 403.
type N403 = ErrorDocument

// N404 defines model for 404.
type N404 = ErrorDocument

// N409 defines model for 409.
type N409 = ErrorDocument

// N500 defines model for 500.
type N500 = ErrorDocument

// CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONBody defines parameters for CreateBreakabilityAnalysisHidden.
type CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONBody struct {
	Data struct {
		Attributes struct {
			PackageUpgrades []Upgrade `json:"package_upgrades"`
		} `json:"attributes"`
		Type CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONBodyDataType `json:"type"`
	} `json:"data"`
}

// CreateBreakabilityAnalysisHiddenParams defines parameters for CreateBreakabilityAnalysisHidden.
type CreateBreakabilityAnalysisHiddenParams struct {
	// Version The requested version of the endpoint to process the request
	Version Version `form:"version" json:"version"`
}

// CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONBodyDataType defines parameters for CreateBreakabilityAnalysisHidden.
type CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONBodyDataType string

// CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONRequestBody defines body for CreateBreakabilityAnalysisHidden for application/vnd.api+json ContentType.
type CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONRequestBody CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONBody

// AsLinkProperty0 returns the union data inside the LinkProperty as a LinkProperty0
func (t LinkProperty) AsLinkProperty0() (LinkProperty0, error) {
	var body LinkProperty0
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLinkProperty0 overwrites any union data inside the LinkProperty as the provided LinkProperty0
func (t *LinkProperty) FromLinkProperty0(v LinkProperty0) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLinkProperty0 performs a merge with any union data inside the LinkProperty, using the provided LinkProperty0
func (t *LinkProperty) MergeLinkProperty0(v LinkProperty0) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsLinkProperty1 returns the union data inside the LinkProperty as a LinkProperty1
func (t LinkProperty) AsLinkProperty1() (LinkProperty1, error) {
	var body LinkProperty1
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromLinkProperty1 overwrites any union data inside the LinkProperty as the provided LinkProperty1
func (t *LinkProperty) FromLinkProperty1(v LinkProperty1) error {
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeLinkProperty1 performs a merge with any union data inside the LinkProperty, using the provided LinkProperty1
func (t *LinkProperty) MergeLinkProperty1(v LinkProperty1) error {
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t LinkProperty) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *LinkProperty) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// CreateBreakabilityAnalysisHiddenWithBody request with any body
	CreateBreakabilityAnalysisHiddenWithBody(ctx context.Context, orgId openapi_types.UUID, params *CreateBreakabilityAnalysisHiddenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	CreateBreakabilityAnalysisHiddenWithApplicationVndAPIPlusJSONBody(ctx context.Context, orgId openapi_types.UUID, params *CreateBreakabilityAnalysisHiddenParams, body CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) CreateBreakabilityAnalysisHiddenWithBody(ctx context.Context, orgId openapi_types.UUID, params *CreateBreakabilityAnalysisHiddenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBreakabilityAnalysisHiddenRequestWithBody(c.Server, orgId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) CreateBreakabilityAnalysisHiddenWithApplicationVndAPIPlusJSONBody(ctx context.Context, orgId openapi_types.UUID, params *CreateBreakabilityAnalysisHiddenParams, body CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBreakabilityAnalysisHiddenRequestWithApplicationVndAPIPlusJSONBody(c.Server, orgId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewCreateBreakabilityAnalysisHiddenRequestWithApplicationVndAPIPlusJSONBody calls the generic CreateBreakabilityAnalysisHidden builder with application/vnd.api+json body
func NewCreateBreakabilityAnalysisHiddenRequestWithApplicationVndAPIPlusJSONBody(server string, orgId openapi_types.UUID, params *CreateBreakabilityAnalysisHiddenParams, body CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateBreakabilityAnalysisHiddenRequestWithBody(server, orgId, params, "application/vnd.api+json", bodyReader)
}

// NewCreateBreakabilityAnalysisHiddenRequestWithBody generates requests for CreateBreakabilityAnalysisHidden with any type of body
func NewCreateBreakabilityAnalysisHiddenRequestWithBody(server string, orgId openapi_types.UUID, params *CreateBreakabilityAnalysisHiddenParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "org_id", runtime.ParamLocationPath, orgId)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/orgs/%s/breakability", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if queryFrag, err := runtime.StyleParamWithLocation("form", true, "version", runtime.ParamLocationQuery, params.Version); err != nil {
			return nil, err
		} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
			return nil, err
		} else {
			for k, v := range parsed {
				for _, v2 := range v {
					queryValues.Add(k, v2)
				}
			}
		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("POST", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// CreateBreakabilityAnalysisHiddenWithBodyWithResponse request with any body
	CreateBreakabilityAnalysisHiddenWithBodyWithResponse(ctx context.Context, orgId openapi_types.UUID, params *CreateBreakabilityAnalysisHiddenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBreakabilityAnalysisHiddenResponse, error)

	CreateBreakabilityAnalysisHiddenWithApplicationVndAPIPlusJSONBodyWithResponse(ctx context.Context, orgId openapi_types.UUID, params *CreateBreakabilityAnalysisHiddenParams, body CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBreakabilityAnalysisHiddenResponse, error)
}

type CreateBreakabilityAnalysisHiddenResponse struct {
	Body                     []byte
	HTTPResponse             *http.Response
	ApplicationvndApiJSON200 *struct {
		// Data breakability assessment
		Data *struct {
			Attributes BreakabilityResponseAttributes `json:"attributes"`
			Id         openapi_types.UUID             `json:"id"`
			Type       Types                          `json:"type"`
		} `json:"data,omitempty"`
		Jsonapi *JsonApi        `json:"jsonapi,omitempty"`
		Links   *PaginatedLinks `json:"links,omitempty"`
	}
	ApplicationvndApiJSON400 *N400
	ApplicationvndApiJSON401 *N401
	ApplicationvndApiJSON403 *N403
	ApplicationvndApiJSON404 *N404
	ApplicationvndApiJSON409 *N409
	ApplicationvndApiJSON500 *N500
}

// Status returns HTTPResponse.Status
func (r CreateBreakabilityAnalysisHiddenResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateBreakabilityAnalysisHiddenResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// CreateBreakabilityAnalysisHiddenWithBodyWithResponse request with arbitrary body returning *CreateBreakabilityAnalysisHiddenResponse
func (c *ClientWithResponses) CreateBreakabilityAnalysisHiddenWithBodyWithResponse(ctx context.Context, orgId openapi_types.UUID, params *CreateBreakabilityAnalysisHiddenParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBreakabilityAnalysisHiddenResponse, error) {
	rsp, err := c.CreateBreakabilityAnalysisHiddenWithBody(ctx, orgId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBreakabilityAnalysisHiddenResponse(rsp)
}

func (c *ClientWithResponses) CreateBreakabilityAnalysisHiddenWithApplicationVndAPIPlusJSONBodyWithResponse(ctx context.Context, orgId openapi_types.UUID, params *CreateBreakabilityAnalysisHiddenParams, body CreateBreakabilityAnalysisHiddenApplicationVndAPIPlusJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBreakabilityAnalysisHiddenResponse, error) {
	rsp, err := c.CreateBreakabilityAnalysisHiddenWithApplicationVndAPIPlusJSONBody(ctx, orgId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBreakabilityAnalysisHiddenResponse(rsp)
}

// ParseCreateBreakabilityAnalysisHiddenResponse parses an HTTP response from a CreateBreakabilityAnalysisHiddenWithResponse call
func ParseCreateBreakabilityAnalysisHiddenResponse(rsp *http.Response) (*CreateBreakabilityAnalysisHiddenResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateBreakabilityAnalysisHiddenResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest struct {
			// Data breakability assessment
			Data *struct {
				Attributes BreakabilityResponseAttributes `json:"attributes"`
				Id         openapi_types.UUID             `json:"id"`
				Type       Types                          `json:"type"`
			} `json:"data,omitempty"`
			Jsonapi *JsonApi        `json:"jsonapi,omitempty"`
			Links   *PaginatedLinks `json:"links,omitempty"`
		}
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest N400
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest N401
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 403:
		var dest N403
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON403 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest N404
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest N409
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 500:
		var dest N500
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationvndApiJSON500 = &dest

	}

	return response, nil
}
